# Use Node.js as the base image
FROM "node:23-alpine3.20"

# Set the working directory
WORKDIR /src

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

CMD [ "npm","start" ]
